# This file contains the deployment configuration for OAuth2 Proxy.
# It includes the necessary environment variables and secret references.
# openssl rand -base64 32
# to generate a random cookie secret
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: default
type: Opaque
stringData:
  client-id: "<YOUR_CLIENT_ID>"
  client-secret: "<YOUR_CLIENT_SECRET>"
  cookie-secret: "<GENERATED_COOKIE_SECRET>"
